### ISSUE TITLE
static copy of the remote handle jar?

### ISSUE THREAD

**Issue by misilot** [jameswsullivan/docker-dspace-handle-server#1]
Would it make sense to build the jar file from source to pull in support for the newer handle server versions?

```
RUN git clone --depth 1 https://github.com/DSpace/Remote-Handle-Resolver.git /tmp/dspace-plugin \
    && cd /tmp/dspace-plugin \
    && mvn clean package \
    && cp /tmp/dspace-plugin/target/dspace-remote-handle-resolver-1.1-SNAPSHOT.jar /opt/handle/lib/ \
    && rm -rf /tmp/dspace-plugin
```

**Comment by jameswsullivan** [comment]
Sure, I thought about doing that but copying feels easier to me and I also wanted to version it the same way as the download, so I didn't go that route.

We can make another branch doing the build?

**Comment by jameswsullivan** [comment]
Hey I'm closing this issue since there's been no updates. Feel free to let me know if we wanna experiment it with a different branch.
